// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9hec_7ixWKkLueLbxO-2QV4FlaX6GPNM',
    appId: '1:862543584022:web:810f5cecf23d5b10850e37',
    messagingSenderId: '862543584022',
    projectId: 'chatapp-f24e1',
    authDomain: 'chatapp-f24e1.firebaseapp.com',
    storageBucket: 'chatapp-f24e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqNQD0z5npYQcFFWIFnd4o4Q1NQyARcAI',
    appId: '1:862543584022:android:b3d240d1c444a75f850e37',
    messagingSenderId: '862543584022',
    projectId: 'chatapp-f24e1',
    storageBucket: 'chatapp-f24e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2zvFaub9hPf_VwSKlOIDxC6TJ-lVurM',
    appId: '1:862543584022:ios:fe85c15e5efb8ed0850e37',
    messagingSenderId: '862543584022',
    projectId: 'chatapp-f24e1',
    storageBucket: 'chatapp-f24e1.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9hec_7ixWKkLueLbxO-2QV4FlaX6GPNM',
    appId: '1:862543584022:web:74be41534968431f850e37',
    messagingSenderId: '862543584022',
    projectId: 'chatapp-f24e1',
    authDomain: 'chatapp-f24e1.firebaseapp.com',
    storageBucket: 'chatapp-f24e1.firebasestorage.app',
  );
}
